##Thanks for using Unify! Support can be found on the Github and in the Developers Server! Links Below

#Github page -> https://github.com/Kurumi78/Un-ify

#My discord -> https://discord.gg/DBBgUMbk3e


Unpathing: true
UnpathingDurability: 1

Untilling: true
UntillingDurability: 1

Unstripping: true
UnstrippingDurability: 1



EnabledUsers:
  -test
  -test2
  -test3
